---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by buis_p.
--- DateTime: 04/07/2019 20:38
---

GovStartImpot = function()

    function startImpot()

        print('Start Impot')
        -- Retrieve gouv account
        TriggerEvent('esx_society:getSociety', 'gouvernor', function(govern)
            if govern ~= nil then

                TriggerEvent('esx_addonaccount:getSharedAccount', govern.account, function(govAccount)

                    if govAccount ~= nil then
                        -- Retrieve Us Custom Account
                        TriggerEvent('esx_society:getSociety', 'custom', function(us_custom)
                            if us_custom ~= nil then
                                -- verified society
                                TriggerEvent('esx_addonaccount:getSharedAccount', us_custom.account, function(uscAccount)
                                    -- does the society money to pay its employees?
                                    local money = round(((uscAccount.money * Config.ImpotValue) / 100), 0)
                                    govAccount.addMoney(money)
                                    uscAccount.removeMoney(money)
                                end)
                            end
                        end)
                    end
                end)

                TriggerEvent('esx_addonaccount:getSharedAccount', govern.account, function(govAccount1)
                    if govAccount1 ~= nil then
                        -- Retrieve Cardealer Account
                        TriggerEvent('esx_society:getSociety', 'cardealer', function(cardealer)
                            if cardealer ~= nil then
                                -- verified society
                                TriggerEvent('esx_addonaccount:getSharedAccount', cardealer.account, function(cardAccount)
                                    -- does the society money to pay its employees?
                                    local money = round(((cardAccount.money * Config.ImpotValue) / 100), 0)
                                    govAccount1.addMoney(money)
                                    cardAccount.removeMoney(money)
                                end)
                            end
                        end)
                    end
                end)

                TriggerEvent('esx_addonaccount:getSharedAccount', govern.account, function(govAccount2)
                    if govAccount2 ~= nil then
                        -- Retrieve Cardealer Account
                        TriggerEvent('esx_society:getSociety', 'banker', function(bank)
                            if bank ~= nil then
                                -- verified society
                                TriggerEvent('esx_addonaccount:getSharedAccount', bank.account, function(bankAccount)
                                    -- does the society money to pay its employees?
                                    local money = round(((bankAccount.money * Config.ImpotValue) / 100), 0)
                                    govAccount2.addMoney(money)
                                    bankAccount.removeMoney(money)
                                end)
                            end
                        end)
                    end
                end)
            end
        end)
        SetTimeout(Config.ImpotInterval, startImpot)
    end
    SetTimeout(Config.ImpotInterval, startImpot)
end

function round(num, numDecimalPlaces)
    local mult = 10^(numDecimalPlaces or 0)
    return math.floor(num * mult + 0.5) / mult
end